apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: arch-gur
type: Opaque
data:
  DATABASE_NAME: {{ .Values.service.db.dbname | b64enc }}
  DATABASE_URL: {{ printf "jdbc:postgresql://%s:%s" .Values.service.db.host .Values.service.db.sport | b64enc }}
  DATABASE_SCHEMA: {{ .Values.service.db.dbschema | b64enc }}
  SPRING_DATASOURCE_USERNAME: YWRtaW4= #admin
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ= #password
  REDIS_PASSWORD: ZVlWWDdFd1ZtbXhLUENEbXdNdHlLVmdlOG9MZDJ0ODE= #eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  CAMUNDA_ADMIN_ID: ZGVtbw== #demo
  CAMUNDA_ADMIN_PASSWORD: ZGVtbw==
  CAMUNDA_ADMIN_FIRSTNAME: ZGVtbw==