package ru.gur.archintercessor.process;

public enum VariableKey {

    PROFILE_ID,
    PRODUCT_ID,
    PROFILE_CHECK_RESULT,
    PRODUCT_CHECK_RESULT,
    PROFILE_DATA,
    STOPLIST_FAIL,
    CLAIM_ID,
    SIGN_KEY_EXPECTED,
    SIGN_KEY_ACTUAL,
    KEY_CHECK_RESULT,
    CANCEL_FLAG,
    AGREEMENT_NUMBER,
    ACCOUNT_ID,
    NEED_PRODUCT_CHANGE,
    NEED_PROFILE_DATA
}
