apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: arch-gur
  labels:
    app: {{ .Values.redis.name }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
  selector:
    app: {{ .Values.redis.name }}