package ru.gur.archintercessor.web.request;

public enum Event {

    NEW_CLAIM_RECEIVED,
    PROFILE_UPDATED,
    PRODUCT_UPDATED,
    AGREEMENT_SIGNED,
    CANCEL_SIGN,
    BROKERAGE_NOTIFICATION,

    CLAIM_IN_PROGRESS,
    CLAIM_WAIT_FOR_SIGN,
    CLAIM_CANCEL,
    CLAIM_DONE,
    CLAIM_REJECTED,
    UPDATE_CLAIM
}
